name: "Qodana analysis"

on: push

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JetBrains/qodana-action@v2022.2.3
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
  qodana-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p ./qodana/logs
      - run: curl -fsSL https://jb.gg/qodana-cli/install | bash
      - run: qodana scan --results-dir=./qodana/logs/ --linter=jetbrains/qodana-php:2022.3-eap
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./qodana/logs/qodana.sarif.json
