name: "Qodana analysis"

on: push

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JetBrains/qodana-action@v2022.2.3
        with:
          args: --linter=jetbrains/qodana-php:2022.3-eap
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
