name: "PHP analysis"

on:
  push:

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Composer Install
        run: composer install
      - run: echo "::add-matcher::.github/problem-matcher.json"
      - name: Run PHPCS
        run: ./vendor/bin/phpcs --report=checkstyle --standard=./phpcs.rulesets.xml ./src/PhpSample.php || true
